// @ts-nocheck
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
//
// To change the Firebase project, use the "Change Firebase Project" command
// from the command palette.
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "p",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id"
};
